HELLP
help with the installation. I did everything I could, installed the python, installed all the updates, but the alienware-kbl does not start. although the icon in the menu is set.
╭─root@debian /  
╰─➤  '/alienware-kbl/setup'
To ensure a clean installation any previous version will be fully removed..
Disabling the systemd daemon...
Removed /etc/systemd/system/basic.target.wants/alienware-kbl.service.
Removing the links to the python bindings...
Removing files and directories..
Copying the software files (the message 'omiting directory *' is normal)...
install: пропускается каталог '/alienware-kbl/usr/share/doc/AlienwareKBL/ImagesPreview'
install: пропускается каталог '/alienware-kbl/usr/share/doc/AlienwareKBL/Licenses'
install: пропускается каталог '/alienware-kbl/usr/share/doc/AlienwareKBL/Programming'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/Configuration'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/Engine'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/__pycache__'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/Configuration/__pycache__'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/Engine/Core'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/Engine/__pycache__'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS/BlockTesting'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS/GUI'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS/Indicator'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS/GUI/images'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS/GUI/__pycache__'
install: пропускается каталог '/alienware-kbl/usr/share/AlienwareKBL/ADDONS/Indicator/images'
Executing the post-installation...
Enabling and starting systemd...
Created symlink /etc/systemd/system/basic.target.wants/alienware-kbl.service → /usr/lib/systemd/system/alienware-kbl.service.
Linking the python bindings...
Python3 linked.
Python3 linked.
Alienware-KBL is installed, enjoy it !
╭─root@debian /  
╰─➤  




╭─root@debian /  
╰─➤  alienware-kbl
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/GUI/GUI.py", line 730, in <module>
    print_error("Failed to start the GUI because the daemon is off.")
NameError: name 'print_error' is not defined
╭─root@debian /  
╰─➤                 






I'm sorry that I ask for help in this way, but I did not think of anything else.